# SwiftLint configuration for Smart Apparel iOS Application
# Version: 1.0.0
# Swift Version: 5.9+

# Disabled rules that conflict with project style or create false positives
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Opt-in rules for enhanced code quality and maintainability
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 75

type_body_length:
  warning: 250
  error: 350

cyclomatic_complexity:
  warning: 10
  error: 15

function_parameter_count:
  warning: 5
  error: 7

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - dx
    - dy

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Included source paths
included:
  - src/ios/SmartApparel/Sources
  - src/ios/SmartApparel/Tests

# Excluded paths
excluded:
  - src/ios/Pods
  - src/ios/SmartApparel.xcodeproj
  - src/ios/SmartApparel.xcworkspace
  - src/ios/fastlane
  - src/ios/vendor

# Reporter type
reporter: "xcode"

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Custom rules for domain-specific requirements
custom_rules:
  sensor_data_validation:
    name: "Sensor Data Validation"
    regex: "(sensor.*data.*validate)"
    message: "Sensor data must be validated before processing"
    severity: warning
  
  bluetooth_error_handling:
    name: "Bluetooth Error Handling"
    regex: "(bluetooth.*connect)(?!.*catch)"
    message: "Bluetooth connections must include error handling"
    severity: error