source "https://rubygems.org"

ruby "3.0.0"

group :development do
  gem "fastlane", "2.217.0"
  gem "cocoapods", "1.12.1"
  gem "xcode-install", "2.8.1"
  gem "xcodeproj", "~> 1.22"
  gem "slack-notifier", "~> 2.4.0"
end

group :test do
  gem "slather", "2.7.2"
end