/**
 * Alert system constants for biomechanical and physiological monitoring
 * @version 1.0.0
 */

/**
 * Comprehensive types of alerts that can be generated by the system
 */
export enum ALERT_TYPES {
  BIOMECHANICAL = 'BIOMECHANICAL',
  PHYSIOLOGICAL = 'PHYSIOLOGICAL', 
  PERFORMANCE = 'PERFORMANCE',
  SYSTEM = 'SYSTEM',
  TECHNIQUE = 'TECHNIQUE',
  FATIGUE = 'FATIGUE',
  COMBINED = 'COMBINED'
}

/**
 * Medical-grade severity levels for alerts requiring immediate response
 */
export enum ALERT_SEVERITY {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
  EMERGENCY = 'EMERGENCY'
}

/**
 * Comprehensive lifecycle states for alert tracking and management
 */
export enum ALERT_STATUS {
  ACTIVE = 'ACTIVE',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  IN_REVIEW = 'IN_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
  ESCALATED = 'ESCALATED'
}

/**
 * Detailed categories for precise classification of alerts
 */
export enum ALERT_CATEGORIES {
  INJURY_RISK = 'INJURY_RISK',
  TECHNIQUE_FAULT = 'TECHNIQUE_FAULT',
  ACUTE_FATIGUE = 'ACUTE_FATIGUE',
  CHRONIC_FATIGUE = 'CHRONIC_FATIGUE',
  CONNECTIVITY = 'CONNECTIVITY',
  PERFORMANCE_DECLINE = 'PERFORMANCE_DECLINE',
  BIOMECHANICAL_ANOMALY = 'BIOMECHANICAL_ANOMALY',
  PHYSIOLOGICAL_STRESS = 'PHYSIOLOGICAL_STRESS'
}

/**
 * Default refresh interval for alert polling in milliseconds
 */
export const DEFAULT_ALERT_REFRESH_INTERVAL = 2500;

/**
 * Maximum number of alerts to display per page
 */
export const MAX_ALERTS_PER_PAGE = 100;

/**
 * Color mapping for alert severity levels using Material Design colors
 */
export const ALERT_SEVERITY_COLORS = {
  LOW: '#4CAF50',      // Green
  MEDIUM: '#FFC107',   // Amber
  HIGH: '#FF9800',     // Orange
  CRITICAL: '#F44336', // Red
  EMERGENCY: '#B71C1C' // Dark Red
} as const;

/**
 * Material icon mappings for alert types
 */
export const ALERT_TYPE_ICONS = {
  BIOMECHANICAL: 'body_scan',
  PHYSIOLOGICAL: 'heartbeat',
  PERFORMANCE: 'analytics',
  SYSTEM: 'settings_suggest',
  TECHNIQUE: 'sports',
  FATIGUE: 'battery_alert',
  COMBINED: 'assessment'
} as const;

/**
 * Weighting factors for alert prioritization algorithm
 * Weights must sum to 1.0
 */
export const ALERT_PRIORITY_WEIGHTS = {
  SEVERITY: 0.4,
  CATEGORY: 0.3,
  AGE: 0.2,
  FREQUENCY: 0.1
} as const;

/**
 * Auto-timeout periods in milliseconds for different severity levels
 * Emergency alerts never timeout automatically
 */
export const ALERT_TIMEOUT_PERIODS = {
  LOW: 3600000,      // 1 hour
  MEDIUM: 1800000,   // 30 minutes
  HIGH: 900000,      // 15 minutes
  CRITICAL: 300000,  // 5 minutes
  EMERGENCY: 0       // No timeout
} as const;

/**
 * Thresholds for alert aggregation to prevent alert fatigue
 */
export const ALERT_AGGREGATION_THRESHOLDS = {
  TIME_WINDOW: 300000,           // 5 minute window
  MAX_SIMILAR: 3,                // Max similar alerts
  CORRELATION_THRESHOLD: 0.85    // Similarity threshold
} as const;