/**
 * Alert system constants and enumerations for smart apparel monitoring
 * @version 1.0.0
 */

/**
 * Defines categories of alerts that can be generated by the system
 */
export enum ALERT_TYPES {
  BIOMECHANICAL = 'BIOMECHANICAL',   // Alerts related to movement and force patterns
  PHYSIOLOGICAL = 'PHYSIOLOGICAL',    // Alerts related to body metrics and vital signs
  PERFORMANCE = 'PERFORMANCE',        // Alerts related to athletic performance metrics
  SYSTEM = 'SYSTEM'                  // Alerts related to system operations and status
}

/**
 * Defines severity levels for alert prioritization
 */
export enum ALERT_SEVERITY {
  LOW = 'LOW',           // Minor issues requiring attention
  MEDIUM = 'MEDIUM',     // Moderate issues requiring timely review
  HIGH = 'HIGH',         // Serious issues requiring prompt attention
  CRITICAL = 'CRITICAL'  // Critical issues requiring immediate action
}

/**
 * Defines possible states in the alert lifecycle
 */
export enum ALERT_STATUS {
  ACTIVE = 'ACTIVE',           // New alert requiring attention
  ACKNOWLEDGED = 'ACKNOWLEDGED', // Alert has been seen but not resolved
  RESOLVED = 'RESOLVED',       // Alert has been addressed and resolved
  DISMISSED = 'DISMISSED'      // Alert has been dismissed as non-actionable
}

/**
 * Evidence-based threshold values for different types of alerts
 * Units:
 * - Force: Newtons (N)
 * - Impact: G-force
 * - Asymmetry: Percentage (%)
 * - ROM_Deviation: Degrees (°)
 * - Acceleration: m/s²
 * - Strain/Fatigue: Percentage (%)
 * - Heart_Rate_Max: Beats per minute (BPM)
 * - Recovery_Time: Seconds (s)
 * - Deviation/Power_Drop: Percentage (%)
 * - Technique_Score: Points (0-100)
 */
export const ALERT_THRESHOLDS = {
  BIOMECHANICAL: {
    FORCE: 850,          // Maximum acceptable force in Newtons
    IMPACT: 10.0,        // Maximum acceptable impact in G-force
    ASYMMETRY: 15.0,     // Maximum acceptable asymmetry percentage
    ROM_DEVIATION: 20.0, // Maximum acceptable range of motion deviation
    ACCELERATION: 12.0   // Maximum acceptable acceleration
  },
  PHYSIOLOGICAL: {
    STRAIN: 85,          // Maximum acceptable strain index
    FATIGUE: 75,         // Maximum acceptable fatigue level
    HEART_RATE_MAX: 195, // Maximum acceptable heart rate
    RECOVERY_TIME: 120   // Minimum required recovery time in seconds
  },
  PERFORMANCE: {
    DEVIATION: 25.0,     // Maximum acceptable performance deviation
    POWER_DROP: 30.0,    // Maximum acceptable power decrease
    TECHNIQUE_SCORE: 65.0 // Minimum acceptable technique score
  }
} as const;

/**
 * Refresh interval for alert polling in milliseconds
 * Set to 5 seconds for optimal balance between responsiveness and system load
 */
export const ALERT_REFRESH_INTERVAL = 5000;

/**
 * Maximum number of alerts to process in a single batch
 * Optimized for system performance and memory usage
 */
export const ALERT_BATCH_SIZE = 100;

/**
 * Number of days to retain alert history
 * Set to 90 days to comply with data retention requirements
 */
export const ALERT_RETENTION_DAYS = 90;

/**
 * Weight factors for alert type prioritization
 * Higher weights indicate higher priority in the alert queue
 */
export const ALERT_PRIORITY_WEIGHTS = {
  BIOMECHANICAL: 1.5,  // Highest priority due to injury prevention focus
  PHYSIOLOGICAL: 1.3,  // High priority for health monitoring
  PERFORMANCE: 1.0,    // Standard priority for performance metrics
  SYSTEM: 0.8         // Lower priority for system operations
} as const;

/**
 * Time window for alert aggregation in milliseconds
 * Set to 5 minutes to prevent alert flooding while maintaining responsiveness
 */
export const ALERT_AGGREGATION_WINDOW = 300000;